// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.5.0.0
//      SpecFlow Generator Version:3.5.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WeatherApi.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("WeatherData-Coordinates", Description="Following Scenarios get the weather data based on Latitude-Longitude", SourceFile="Features\\Weather-Coordinates.feature", SourceLine=0)]
    public partial class WeatherData_CoordinatesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "Weather-Coordinates.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "WeatherData-Coordinates", "Following Scenarios get the weather data based on Latitude-Longitude", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void WeatherDataBasedOnLatitudesAndLongitudes(string comments, string latitude, string longitude, string expectedResponse, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Comments", comments);
            argumentsOfScenario.Add("Latitude", latitude);
            argumentsOfScenario.Add("Longitude", longitude);
            argumentsOfScenario.Add("ExpectedResponse", expectedResponse);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Weather Data based on Latitudes and Longitudes", null, tagsOfScenario, argumentsOfScenario);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
testRunner.Given(string.Format("I am a user who wants to get the weather details based on its {0} and {1}", latitude, longitude), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
testRunner.When("I look up the weather forecast as an authenticated user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
testRunner.Then(string.Format("the Api response code should be \'{0}\'", expectedResponse), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Comments",
                            "clouds",
                            "snow",
                            "precip",
                            "sunrise",
                            "sunset",
                            "date_time",
                            "temp"});
                table1.AddRow(new string[] {
                            "All parameters are approximations. Values in this table are not utilized but can " +
                                "be used with small change. There is also a bug such that sunrise time is after s" +
                                "unset",
                            "0",
                            "0",
                            "0",
                            "",
                            "",
                            "0",
                            "0"});
#line 8
testRunner.And("I receive the weather forecast with the following parameters", ((string)(null)), table1, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Weather Data based on Latitudes and Longitudes, Sydney", SourceLine=13)]
        public virtual void WeatherDataBasedOnLatitudesAndLongitudes_Sydney()
        {
#line 4
this.WeatherDataBasedOnLatitudesAndLongitudes("Sydney", "-33.86", "151.21", "OK", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Weather Data based on Latitudes and Longitudes, Tokyo", SourceLine=13)]
        public virtual void WeatherDataBasedOnLatitudesAndLongitudes_Tokyo()
        {
#line 4
this.WeatherDataBasedOnLatitudesAndLongitudes("Tokyo", "35.65", "139.74", "OK", ((string[])(null)));
#line hidden
        }
        
        public virtual void WeatherDataBasedOnLatitudesAndLongitudes_NegativeScenarios(string comments, string latitude, string longitude, string expectedResponse, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Comments", comments);
            argumentsOfScenario.Add("Latitude", latitude);
            argumentsOfScenario.Add("Longitude", longitude);
            argumentsOfScenario.Add("ExpectedResponse", expectedResponse);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Weather Data based on Latitudes and Longitudes - Negative Scenarios", null, tagsOfScenario, argumentsOfScenario);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
testRunner.Given(string.Format("I am a user who wants to get the weather details based on its {0} and {1}", latitude, longitude), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
testRunner.When("I look up the weather forecast as an authenticated user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
testRunner.Then(string.Format("the Api response code should be \'{0}\'", expectedResponse), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Weather Data based on Latitudes and Longitudes - Negative Scenarios, Variant 0", SourceLine=24)]
        public virtual void WeatherDataBasedOnLatitudesAndLongitudes_NegativeScenarios_Variant0()
        {
#line 18
this.WeatherDataBasedOnLatitudesAndLongitudes_NegativeScenarios("Sydney", "", "151.21", "BadRequest", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Weather Data based on Latitudes and Longitudes - Negative Scenarios, Variant 1", SourceLine=24)]
        public virtual void WeatherDataBasedOnLatitudesAndLongitudes_NegativeScenarios_Variant1()
        {
#line 18
this.WeatherDataBasedOnLatitudesAndLongitudes_NegativeScenarios("Sydney", "-33.86", "", "BadRequest", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Weather Data based on Latitudes and Longitudes - Negative Scenarios, Variant 2", SourceLine=24)]
        public virtual void WeatherDataBasedOnLatitudesAndLongitudes_NegativeScenarios_Variant2()
        {
#line 18
this.WeatherDataBasedOnLatitudesAndLongitudes_NegativeScenarios("Sydney", "", "", "BadRequest", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
